// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssasxtrpgbbgfprbizzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYXN4dHJwZ2JiZ2ZwcmJpenpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDc1NDYsImV4cCI6MjA2NTUyMzU0Nn0.waYMWeVTKKeDg2SYUgguqkBw7WxsSWQTYl6253obPJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);